/** Locale-owned Browser annotation copy. */
export const zh = {
  openBrowser: '批注网页',
  start: '添加批注',
  stop: '退出批注',
  select: '点击任意位置即可添加批注，也可拖动选取区域。按住空格键时可暂时操作网页。',
  interact: '正在操作网页 · 松开空格键返回批注',
  comment: '评论',
  question: '提问',
  placeholder: '添加评论…',
  settings: '批注选项',
  save: '保存批注',
  cancel: '取消',
  parent: '选择父级元素',
  child: '返回子级元素',
  targetGone: '页面目标已变化，请重新选择',
  empty: '请先输入评论或问题',
  region: '框选区域',
  point: '页面位置',
  notes: '页面批注',
  remove: '删除批注',
  preview: '预览发送内容',
  send: '发送到当前会话',
  draft: '加入输入框',
  sent: '已发送到当前会话',
  inserted: '已加入输入框',
  unavailable: '此页面暂时无法批注。Web 预览需启用开发页面连接；桌面版需配套 Browser 扩展',
  pageChanged: '页面已变化，请重新选择',
  limit: '批注过多，请分批发送',
  failed: '操作失败，批注已保留',
  timeout: '批注操作超时，请重试',
  queue: '发送内容',
  addMore: '继续添加',
  color: '文本颜色',
  background: '背景',
  opacity: '不透明度',
  font: '字体',
  fontSize: '字号',
  fontWeight: '字重',
  spacing: '间距',
  elementOnly: '框选区域保留真实范围；点选元素后可调整属性',
  invalidStyle: '属性值无效，请检查后再保存',
  applyStyles: '应用这些样式调整',
  styleHint: '属性调整会随批注交给 AI 修改源码',
  delivery: '发送方式',
  image: '图片',
  details: '定位资料',
  both: '图片＋定位资料',
  evidence: '查看定位资料',
  noImage: '这条批注没有截图，可发送定位资料或重新批注',
  saving: '正在保存批注…',
  storageFailed: '批注暂时无法保存在本机，刷新或关闭前请先发送',
} as const;
export type AnnotationCopyKey = keyof typeof zh;
export const en: Record<AnnotationCopyKey, string> = {
  openBrowser: 'Annotate page',
  start: 'Add annotation',
  stop: 'Exit annotation',
  select:
    'Click anywhere to annotate, or drag to select an area. Hold Space to interact with the page.',
  interact: 'Interacting with page · Release Space to annotate',
  comment: 'Comment',
  question: 'Question',
  placeholder: 'Add a comment…',
  settings: 'Annotation options',
  save: 'Save annotation',
  cancel: 'Cancel',
  parent: 'Select parent element',
  child: 'Return to child element',
  targetGone: 'The target changed. Select it again.',
  empty: 'Enter a comment or question first.',
  region: 'Selected area',
  point: 'Page position',
  notes: 'Page annotations',
  remove: 'Remove annotation',
  preview: 'Preview request',
  send: 'Send to current session',
  draft: 'Add to composer',
  sent: 'Sent to current session',
  inserted: 'Added to composer',
  unavailable:
    'This page cannot be annotated yet. Web preview needs the development bridge; Desktop needs the Browser extension.',
  pageChanged: 'The page changed. Select it again.',
  limit: 'Too many annotations. Send a smaller batch.',
  failed: 'The operation failed. Your annotations were kept.',
  timeout: 'Annotation timed out. Try again.',
  queue: 'Request',
  addMore: 'Add more',
  color: 'Text color',
  background: 'Background',
  opacity: 'Opacity',
  font: 'Font',
  fontSize: 'Font size',
  fontWeight: 'Font weight',
  spacing: 'Spacing',
  elementOnly: 'Areas keep their exact bounds. Select an element to adjust properties.',
  invalidStyle: 'Check the property values before saving.',
  applyStyles: 'Apply these style changes',
  styleHint: 'Property changes are sent with the annotation for the AI to edit source.',
  delivery: 'Send as',
  image: 'Image',
  details: 'Location details',
  both: 'Image + details',
  evidence: 'View location details',
  noImage: 'This annotation has no screenshot. Send its location details or select it again.',
  saving: 'Saving annotations…',
  storageFailed:
    'Annotations could not be saved on this device. Send them before reloading or closing.',
};
declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    webAnnotatorAnnotations: AnnotationCopyKey;
  }
}
