export const zh = {
  subtitle: '检查布局，保留好的设计。',
  requestTooLarge: '修改要求过大或内容无效，请减少勾选项或批注后重试。',
  url: '本地开发页面',
  connect: '连接',
  startTitle: '把前端页面带进当前会话',
  bridgeHelp:
    '在项目的 Vite 配置中加入 webAnnotator()，启动开发服务器，然后连接页面。连接失败时检查页面是否能打开，以及是否已安装开发桥接。',
  localOnly: '支持带明确端口的本机 HTTP 地址，例如 http://localhost:5173。',
  connected: '页面已连接',
  connecting: '正在连接页面…',
  reload: '重新加载',
  viewport: '预览宽度',
  fit: '显示比例',
  pagePreview: 'DSH Web Annotator 网页预览',
  scan: '检测当前宽度',
  scanAll: '检测三个宽度',
  annotate: '标注修改',
  protect: '标记保留',
  cancel: '取消选择',
  picking: '选择页面元素',
  pickHelp: '在上方页面点击元素；Esc 或“取消选择”退出。',
  scanDone: '检测完成。请确认哪些候选确实需要修改。',
  annotationAdded: '已添加批注，请填写修改要求。',
  protectionAdded: '已记录保留区域的文字、样式和位置。',
  recheck: '复查保留区域',
  recheckDone: '复查完成。结果见保留区域列表。',
  candidates: '布局候选',
  chooseCandidates: '勾选后才进入修改要求',
  noCandidates: '当前检测未发现候选。仍需检查页面内容与交互。',
  scanHelp: '检测超出视口的元素，主动滚动和裁切区域会被排除。',
  horizontalOverflow: '页面横向溢出',
  viewportOverflow: '元素超出视口',
  locate: '定位',
  intentional: '这是预期布局',
  ignored: '已忽略的元素',
  restore: '恢复检测',
  annotations: '修改批注',
  annotationHelp: '选择页面元素，把“这里”变成有定位和视口信息的修改要求。',
  note: '修改要求',
  notePlaceholder: '例如：小屏下改为单列，保留原有字体和按钮样式。',
  remove: '移除',
  protections: '保留区域',
  protectionHelp:
    '在记录时的宽度复查文字、计算样式与几何位置。2px 内偏差会被容忍；结果不覆盖区域内所有子元素和交互。',
  protectionLabel: '保留说明',
  lastCheck: '上次复查',
  notChecked: '尚未复查',
  unchanged: '未发现变化',
  changed: '有变化',
  missing: '目标已消失',
  ambiguous: '目标不唯一',
  previewRequest: '预览修改要求',
  hideRequest: '收起修改要求',
  addDraft: '加入草稿',
  send: '发送到当前会话',
  queue: '排队发送',
  sending: '正在发送',
  request: '将发送的修改要求',
  submitHelp: '仅发送填写的批注、勾选的候选与保留区域。先确认当前会话对应这个前端项目。',
  draftAdded: '已插入当前草稿。',
  sent: '修改要求已提交到当前会话。修改后请重新检测与复查。',
  draftChanged: '草稿已变更或暂不可编辑，请重试。',
  sessionMissing: '当前会话不可用，请重新打开插件。',
  storageError: '浏览器未能保存批注。当前内容仍可使用，关闭前请加入草稿。',
  reloaded: '页面已重新加载，请重新操作。',
  timeout: '页面响应超时，请重新加载后重试。',
  invalidResponse: '页面返回的数据无效，请检查桥接版本。',
};
export type CopyKey = keyof typeof zh;
export const en: Record<CopyKey, string> = {
  requestTooLarge:
    'The request is too large or invalid. Select fewer items or remove some annotations.',
  subtitle: 'Check layouts. Preserve good design.',
  url: 'Local development page',
  connect: 'Connect',
  startTitle: 'Bring your frontend into this conversation',
  bridgeHelp:
    'Add webAnnotator() to your Vite config, start the development server, then connect the page. If connection fails, check the page and the development bridge.',
  localOnly: 'Use a local HTTP address with an explicit port, such as http://localhost:5173.',
  connected: 'Page connected',
  connecting: 'Connecting…',
  reload: 'Reload page',
  viewport: 'Preview width',
  fit: 'Scale',
  pagePreview: 'DSH Web Annotator page preview',
  scan: 'Scan this width',
  scanAll: 'Scan three widths',
  annotate: 'Annotate change',
  protect: 'Protect region',
  cancel: 'Cancel selection',
  picking: 'Select an element',
  pickHelp: 'Click an element in the preview. Esc or Cancel selection exits.',
  scanDone: 'Scan complete. Confirm which candidates need changes.',
  annotationAdded: 'Annotation added. Describe the requested change.',
  protectionAdded: 'Region text, styles and geometry recorded.',
  recheck: 'Recheck protected regions',
  recheckDone: 'Recheck complete. See the protected regions below.',
  candidates: 'Layout candidates',
  chooseCandidates: 'Only checked items enter the request',
  noCandidates: 'No candidates found in scanned widths. Still review content and interactions.',
  scanHelp:
    'Find elements exceeding the viewport. Intentional scrolling and clipping are excluded.',
  horizontalOverflow: 'Page overflows horizontally',
  viewportOverflow: 'Element exceeds viewport',
  locate: 'Locate',
  intentional: 'Intentional layout',
  ignored: 'Ignored elements',
  restore: 'Restore scanning',
  annotations: 'Change annotations',
  annotationHelp: 'Select an element to attach a target and viewport to your request.',
  note: 'Requested change',
  notePlaceholder:
    'For example: use one column on mobile; preserve existing typography and buttons.',
  remove: 'Remove',
  protections: 'Protected regions',
  protectionHelp:
    'Recheck text, computed styles and geometry at the recorded width. Differences within 2px are tolerated. This does not cover every descendant or interaction.',
  protectionLabel: 'Preservation note',
  lastCheck: 'Last check',
  notChecked: 'Not checked yet',
  unchanged: 'No changes found',
  changed: 'Changed',
  missing: 'Target missing',
  ambiguous: 'Target is not unique',
  previewRequest: 'Preview request',
  hideRequest: 'Hide request',
  addDraft: 'Add to draft',
  send: 'Send to current conversation',
  queue: 'Queue request',
  sending: 'Sending',
  request: 'Request to be sent',
  submitHelp:
    'Send written annotations, checked candidates and protected regions. Confirm that this conversation belongs to the frontend project.',
  draftAdded: 'Inserted into the current draft.',
  sent: 'Submitted to the current conversation. Scan and recheck after edits.',
  draftChanged: 'The draft changed or is locked. Try again.',
  sessionMissing: 'The current conversation is unavailable. Reopen the plugin.',
  storageError:
    'The browser could not save the review. You can still use it; add it to the draft before closing.',
  reloaded: 'The page reloaded. Please retry.',
  timeout: 'The page timed out. Reload and try again.',
  invalidResponse: 'Invalid page response. Check the bridge version.',
};
